#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <openssl/evp.h>
#include <openssl/sha.h>


unsigned char* Read_File(char fileName[], int *fileLen);
void Write_File(char fileName[], char input[], int input_length);
void Convert_to_Hex(char output[], unsigned char input[], int inputlength);
void Show_in_Hex(char name[], unsigned char hex[], int hexlen);
unsigned char* PRNG(unsigned char *seed, unsigned long seedlen, unsigned long prnglen);
unsigned char* Hash_SHA256(unsigned char* input, unsigned long inputlen);

unsigned char hex_to_byte(char hex1, char hex2);

int main(int argc, char *argv[]) {

    // check that the correct number of command line arguments are provided
    if (argc < 2) {
        return 1;
    }
    
    //reads the cyphertext generated by alice and 
    int cyphertext_len = 0;
    unsigned char *cyphertext = Read_File("Ciphertext.txt", &cyphertext_len);
    if (cyphertext_len % 2 != 0) 
    {
        printf("Error: ciphertext hex length must be even.\n");
        free(cyphertext);
        return 1;
    }

    //convert the cyphertext form hexadecimal back to bytes
    int raw_len = cyphertext_len / 2;
    for (int i = 0; i < raw_len; i++) {
        cyphertext[i] = hex_to_byte(cyphertext[2*i], cyphertext[2*i + 1]);
    }
    cyphertext_len = raw_len;



    //reads seed from file and generatesprng from it
    int seed_len = 0;
    unsigned char *seed = Read_File(argv[1], &seed_len);

    unsigned char *pseudoRandomNumber = PRNG(seed, seed_len, cyphertext_len);
    unsigned char *plaintext = malloc(cyphertext_len);

    //xor the cyphertext ot get the plaintext
    for (int i = 0; i < cyphertext_len; i++) {
        plaintext[i] = cyphertext[i] ^ pseudoRandomNumber[i];
    }

    //write the plaintext to the file
    Write_File("Plaintext.txt", plaintext, cyphertext_len);

    //hash the plaintext and write it to the hash file
    unsigned char *hash = Hash_SHA256(plaintext, cyphertext_len);
    char hash_hex[64 + 1];
    Convert_to_Hex(hash_hex, hash, 32);
    Write_File("Hash.txt", hash_hex, 64);

    // free the memory to make sure there are no leaks
    free(cyphertext);
    free(seed);
    free(pseudoRandomNumber);
    free(plaintext);
    free(hash);

    return 0;
}

/*************************************************************
                    F u n c t i o n s
**************************************************************/
unsigned char hex_to_byte(char hex1, char hex2) {
    unsigned char most_s, least_s;

    if (hex1 >= '0' && hex1 <= '9') 
    {
        most_s = hex1 - '0';
    } 
    else if (hex1 >= 'a' && hex1 <= 'f') {
        most_s = hex1 - 'a' + 10;
    } 
    else if (hex1 >= 'A' && hex1 <= 'F') {
        most_s = hex1 - 'A' + 10;
    } 
    
    else {
        most_s = 0; 
    }

    if (hex2 >= '0' && hex2 <= '9') 
    {
        least_s = hex2 - '0';
    }
    else if (hex2 >= 'a' && hex2 <= 'f') 
    {
        least_s = hex2 - 'a' + 10;
    }
    else if (hex2 >= 'A' && hex2 <= 'F') 
    {
        least_s = hex2 - 'A' + 10;
    }
    else 
    {
        least_s = 0; 
    }

    return (most_s << 4) | least_s;
}


/*============================
        Read from File
==============================*/
unsigned char* Read_File(char fileName[], int *fileLen)
{
    FILE *pFile;
    pFile = fopen(fileName, "r");
    if (pFile == NULL)
    {
        printf("Error opening file.\n");
        exit(0);
    }
    fseek(pFile, 0L, SEEK_END);
    int temp_size = ftell(pFile) + 1;
    fseek(pFile, 0L, SEEK_SET);
    unsigned char *output = (unsigned char*) malloc(temp_size);
    fgets(output, temp_size, pFile);
    fclose(pFile);

    *fileLen = temp_size - 1;
    return output;
}

/*============================
        Write to File
==============================*/
void Write_File(char fileName[], char input[], int input_length){
  FILE *pFile;
  pFile = fopen(fileName,"w");
  if (pFile == NULL){
    printf("Error opening file. \n");
    exit(0);
  }
  //fputs(input, pFile);
  fwrite(input, 1, input_length, pFile);
  fclose(pFile);
}

/*============================
        Showing in Hex 
==============================*/
void Show_in_Hex (char name[], unsigned char hex[], int hexlen)
{
    printf("%s: ", name);
    for (int i = 0 ; i < hexlen ; i++)
        printf("%02x", hex[i]);
    printf("\n");
}

/*============================
        Convert to Hex 
==============================*/
void Convert_to_Hex(char output[], unsigned char input[], int inputlength)
{
    for (int i=0; i<inputlength; i++){
        sprintf(&output[2*i], "%02x", input[i]);
    }
    printf("Hex format: %s\n", output);  //remove later
}

/*============================
        PRNG Fucntion 
==============================*/
unsigned char* PRNG(unsigned char *seed, unsigned long seedlen, unsigned long prnglen)
{
    EVP_CIPHER_CTX *ctx = EVP_CIPHER_CTX_new();
    unsigned char *pseudoRandomNumber = malloc(prnglen);

    unsigned char nonce[16] = {0};

    EVP_EncryptInit_ex(ctx, EVP_chacha20(), NULL, seed, nonce);

    unsigned char zeros[prnglen];
    memset(zeros, 0, prnglen);

    int outlen;
    EVP_EncryptUpdate(ctx, pseudoRandomNumber, &outlen, zeros, prnglen);
    EVP_EncryptFinal(ctx, pseudoRandomNumber, &outlen);

    EVP_CIPHER_CTX_free(ctx);
    return pseudoRandomNumber;
}

/*============================
        SHA-256 Fucntion
==============================*/
unsigned char* Hash_SHA256(unsigned char* input, unsigned long inputlen)
{
    unsigned char *hash = malloc(SHA256_DIGEST_LENGTH);

    EVP_MD_CTX *ctx = EVP_MD_CTX_new();
    EVP_DigestInit_ex(ctx, EVP_sha256(), NULL);
    EVP_DigestUpdate(ctx, input, inputlen);
    EVP_DigestFinal_ex(ctx, hash, NULL);
    EVP_MD_CTX_free(ctx);

    return hash;
}